repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform.git
    rev: v1.68.1
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
#      - id: terraform_tfsec
      - id: terraform_validate
