name: Static Analysis

on:
  push:
    branches:
      - main

jobs:
  static_analysis:
    runs-on: ubuntu-22.04

    steps:
      - name: Static Analysis
        uses: pagopa/eng-github-actions-iac-template/azure/terraform-static-analysis@59c12b7a846423d62c27c9905686a7a1fd71c003 # v1.7.0
        with:
          precommit_version: 'v1.92.2@sha256:f809e53ddfcab9fbeb0d58adaf0c44f5dfc8e706'
